// Generated by CoffeeScript 1.6.2
(function() {
  var UrlShortener,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  UrlShortener = (function() {
    function UrlShortener(url) {
      var _this = this;

      this.url = url;
      this.openUrlDetails = __bind(this.openUrlDetails, this);
      this.copyUrlToClipboard = __bind(this.copyUrlToClipboard, this);
      this.handleResponse = __bind(this.handleResponse, this);
      $('#copy-url').click(this.copyUrlToClipboard);
      $('#url-details').click(this.openUrlDetails);
      chrome.tabs.getSelected(null, function(tab) {
        return _this.shortenUrl(tab.url);
      });
    }

    UrlShortener.prototype.shortenUrl = function(url) {
      return $.ajax({
        type: "POST",
        url: this.url,
        data: {
          url: url
        },
        success: this.handleResponse,
        dataType: 'json'
      });
    };

    UrlShortener.prototype.handleResponse = function(data) {
      this.id = data["id"];
      this.short_name = data["short_name"];
      return this.renderShortUrl();
    };

    UrlShortener.prototype.renderShortUrl = function() {
      return $('.shortcode').html(this.short_name);
    };

    UrlShortener.prototype.copyUrlToClipboard = function() {
      var url;

      if (this.short_name != null) {
        url = "" + this.url + "/" + this.short_name;
        $('#sandbox').val(url).select();
        document.execCommand('copy');
        return $('#sandbox').val('');
      }
    };

    UrlShortener.prototype.openUrlDetails = function() {
      if (this.id != null) {
        return chrome.tabs.create({
          url: "" + this.url + "/short_urls/" + this.id
        });
      }
    };

    return UrlShortener;

  })();

  $(document).ready(function() {
    return new UrlShortener("http://wcmc.io");
  });

}).call(this);
