// Generated by CoffeeScript 1.6.2
(function() {
  var UrlShortener,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  UrlShortener = (function() {
    function UrlShortener(url) {
      var _this = this;

      this.url = url;
      this.openUrlDetails = __bind(this.openUrlDetails, this);
      this.copyUrlToClipboard = __bind(this.copyUrlToClipboard, this);
      this.handleResponse = __bind(this.handleResponse, this);
      document.getElementById('copy-url').onclick = this.copyUrlToClipboard;
      document.getElementById('url-details').onclick = this.openUrlDetails;
      chrome.tabs.getSelected(null, function(tab) {
        return _this.shortenUrl(tab.url);
      });
    }

    UrlShortener.prototype.shortenUrl = function(url) {
      var http, params,
        _this = this;

      http = new XMLHttpRequest();
      params = "{\"url\": \"" + url + "\"}";
      http.open("POST", this.url, true);
      http.setRequestHeader("Content-type", "application/json");
      http.setRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01");
      http.onreadystatechange = function() {
        if (http.readyState === 4 && http.status === 201) {
          return _this.handleResponse(http.responseText);
        }
      };
      return http.send(params);
    };

    UrlShortener.prototype.handleResponse = function(data) {
      data = JSON.parse(data);
      this.id = data["id"];
      this.short_name = data["short_name"];
      return this.renderShortUrl();
    };

    UrlShortener.prototype.renderShortUrl = function() {
      return document.getElementById('shortcode').innerHTML = this.short_name;
    };

    UrlShortener.prototype.copyUrlToClipboard = function() {
      var sandboxEl, url;

      if (this.short_name != null) {
        url = "" + this.url + "/" + this.short_name;
        sandboxEl = document.getElementById('sandbox');
        sandboxEl.value = url;
        sandboxEl.select();
        document.execCommand('copy');
        return sandboxEl.value = '';
      }
    };

    UrlShortener.prototype.openUrlDetails = function() {
      if (this.id != null) {
        return chrome.tabs.create({
          url: "" + this.url + "/short_urls/" + this.id
        });
      }
    };

    return UrlShortener;

  })();

  new UrlShortener("http://wukumurl.unepwcmc-005.vm.brightbox.net");

}).call(this);
